### ISSUE TITLE
ldaps issue

### ISSUE THREAD

**Issue by dave-irvine** [jeremycx/node-LDAP#80] opened 2015-11-05 10:41 UTC
I get the feeling this will be fun to debug, but here we go.

Previously on 1.x (node 0.10.x) I was able to successfully connect and query my LDAP server using LDAPS (uri: "ldaps://x.y.z"), however this has subsequently broken with the 2.0.7 release (and an upgrade to node 5.x).

If I call `bind` after this:

```
var ldapClient = require('ldap-client');
var uri = 'ldaps://x.y.z';
var ldap = new ldapClient({
    uri: uri,
    starttls: false
});
```
then I eventually get:

```
{ [LDAPError: Timeout] name: 'LDAPError', message: 'Timeout' }
```

after a pause.

I'm not using starttls, just ldaps, and as I said, this worked before.

By the look of the traffic on the server side, there is no SSL initiation going on, although the connection arrives on the correct port.

Any clues would be great!

**Comment by dave-irvine** [comment] 2015-11-05 11:18
If I drop the 2.0.7 release and pull straight from master (I see there are a few unpublished commits), then I get:

```
node: ../LDAPCnx.cc:71: static void LDAPCnx::Event(uv_poll_t*, int, int): Assertion `status == 0' failed.
```

Don't know if this is related or just because master is broken

**Comment by jeremycx** [comment] 2015-11-05 17:26
2.0.7 doesn't even have TLS support :) 

As far as master goes, TLS still isn't quite complete yet - I ran into a ton of problems with automatic reconnection under TLS - I should have something ready at the end of today.

**Comment by jeremycx** [comment] 2015-11-05 18:51
Alright, pushed 3.0.0 -- give it a try, close if you're happy :)

**Comment by dave-irvine** [comment] 2015-11-06 11:30
I'm now getting the assertion failure again unfortunately

```
node: ../LDAPCnx.cc:95: static void LDAPCnx::Event(uv_poll_t*, int, int): Assertion `status == 0' failed.
```

**Comment by jeremycx** [comment] 2015-11-06 16:15
I forgot to clobber an assert(), but that also means that assert isn't firing for me. Hmmm.

I removed the assert, pull from master and try it now.

**Comment by dave-irvine** [comment] 2015-11-09 08:17
OK the assert has gone but now we're back to

```
{ [LDAPError: Timeout] name: 'LDAPError', message: 'Timeout' }
```

:( not sure what is happening here, as soon as I switch back to old node and old ldap-client, everything works again!

**Comment by jeremycx** [comment] 2015-11-09 16:11
Can you give me a small code sample that exhibits the issue above?

**Comment by dave-irvine** [comment] 2015-11-09 17:20
Sure:

```
var uri = ldapConfig.schema + ldapConfig.host;

var LDAP = require("ldap-client");
var ldap = new LDAP({
    uri: uri
});

function doBind(cb) {
    var bind_options = {
        binddn: ldapConfig.binddn,
        password: ldapConfig.password
    };

    ldap.bind(bind_options, function (err) {
        if (err) {
            console.log(err);
            ldap.close();
            return;
        }

        if (cb) { cb(); }
    });
}

doBind(function () {
    console.log('bind ok!');
});
```

Where `ldapConfig` has similar properties to the following, obviously using real values but replaced here:

```
schema: 'ldaps://',
host: 'my.ldap.server',
binddn: 'ldapuser@my.domain',
password: 'ldapuserspassword'
```

**Comment by jeremycx** [comment] 2015-11-09 18:46
I'm betting you're connecting via ldaps to a server with a self-signed certificate. The default in the new version is to reject bad certs by default. You can switch this off though:

```javascript
var ldap = new LDAP({
    uri: 'ldaps://localhost',
    validatecert: LDAP.LDAP_OPT_X_TLS_NEVER'
}, function(err) {
    // connection ready
});
```
Also, your binddn above isn't a dn, but this makes me curious - I've seen (somewhere) some kind of automapping between dc=my,dc=domain and cn so you **can** do something like the above -- do you have any background on why you expected ldapuser@my.domain to work in the first place (I'm thinking there may be a switch I can turn on somewhere or something to get this behaviour from the underlying library).

**Comment by Alaneor** [comment] 2015-11-09 18:53
@jeremycx That *binddn* is one of the user authentication formats supported by Active Directory, in this particular case, I believe it's *userPrincipalName*.

You can read about all the supported formats [here][msdn], if you like.

[msdn]: https://msdn.microsoft.com/en-us/library/cc223499.aspx

**Comment by jeremycx** [comment] 2015-11-09 18:56
That's a nice server feature.. :)

Please close this Issue if things are working now, but get back in touch if there's still problems.

**Comment by dave-irvine** [comment] 2015-11-10 08:01
Self-signed cert was my first thought but our server is properly certified. I've used the option you provided and I'm still getting a timeout.

I use the command line `ldapsearch` tool to check that the underlying OpenLDAP library is able to connect (this continues to work fine), and historically I've used the @ format binddn with this tool so I just carried this over when I started using ldap-client.

I'm just really confused why this works with the old version of this and not the new one. I've trawled through your source and I can't see anything really that you used to pass to the underlying library and are no longer passing. I'm a bit stumped :(

**Comment by dave-irvine** [comment] 2015-11-10 08:05
I suppose it is worth noting that I've been sniffing traffic on our LDAP server.

Using the old version of the lib, the first traffic to arrive (after some preamble) when I call `open()` is the SSL negotiation, I can see the certificates passing over, and then all future traffic is encrypted and I can see nothing else in plaintext.

With the *new* version of the lib, the first traffic to arrive (after some preamble) is the binddn and password, in plaintext, and *then* the SSL negotiation, however no additional traffic follows.

So my feeling is the new version is doing things the wrong way around, maybe related to us no longer being able to explicitly call `open()`?

**Comment by jeremycx** [comment] 2015-11-10 18:55
This is likely to be a tough problem, but I'm willing to work through it until it works, if you have the patience.

The way the async aspects of openLDAP libs work means I need to send an anonymous bind() to kickstart the connection process, so if the first bind() you see is anonymous - then things are working properly. Can you double-check that the bind you are seeing before TLS is indeed anonymous?

Second note: if (and I'm not sure about the internals on this one) the non-anon bind() does not wait for the ready callback from `new LDAP(opt, ready_callback)`, then it's possible the initial bind() will be unencrypted (as the StartTLS PDU is still in transit as the first non-anon bind() is sent:

1. Connect Socket
2. Send StartTLS PDU
3. Send initial non-anon bind()
4. StartTLS Response (subsequent reqs are now encrypted)
5. Bind() Response (unencrpted)

All of the above is academic, though - we still need to work out your Timeout issue (which is most likely TLS-related, the errors coming back from the TLS parts are not very descriptive, but this may be realted to how I'm retrieving them, for sure).

So, can you send a new code sample that fails, so I can (hopefully) see what's going on?

**Comment by dave-irvine** [comment] 2015-11-11 08:07
Ah, interesting. I hadn't noticed that you'd changed the signature for `new LDAP()`.

Now we can make the failing sample even smaller!

```
var uri = ldapConfig.schema + ldapConfig.host;

var LDAP = require("ldap-client");

var ldap = new LDAP({
    uri: uri,
    validatecert: LDAP.LDAP_OPT_X_TLS_NEVER
}, function (err) {
    if (err) {
        return console.log(err);
    }

    console.log('init ok');
});
```

Where ldapConfig is again like:

```
schema: 'ldaps://',
host: 'my.ldap.server'
```

I'll do some more packet sniffing a bit later today.

**Comment by jeremycx** [comment] 2015-11-12 16:42
In my test env, the above code works fine, as long as I specify the host and port correctly.

Since adding a port in ldapConfig for my test server made it connect OK, I'm maybe thinking there's a port number issue here. Using ldaps:// without specifying a port makes a connection to port 636(ldaps) - can you verify this port is open and accepting connections on your server?

(If you're developing on a UNIX-y machine, there is a "run_server.sh" script in /test that will load data into and subsequently run a custom slapd instance with some test data in it. ldap on port 1234 and ldaps on port 1235).

**Comment by dave-irvine** [comment] 2015-11-12 17:31
Yes we're still trying to solve the timeout issue :)

Happy to run the slapd test, however the real-world use case here is against Active Directory.

The server is definitely running on 636, this is the port I've been sniffing on. No we aren't using referrals.

**Comment by dave-irvine** [comment] 2015-11-12 17:53
Haven't got slapd running yet, but I've tried just using openssl as a test server for checking whether the library is connecting over SSL properly:

```
sudo openssl s_server -accept 636 -key /etc/ssl/private/ssl-cert-snakeoil.key -cert /etc/ssl/certssl-cert-snakeoil.pem
```

If I connect to this using openssl in client mode, everything is fine (obviously a self-signed cert error).

When I connect using the library, we get:

```
ACCEPT
ERROR
140593133323936:error:140940F5:SSL routines:SSL3_READ_BYTES:unexpected record:s3_pkt.c:1424:
shutting down SSL
CONNECTION CLOSED
```

So looks like the packets are malformed somehow?

**Comment by jeremycx** [comment] 2015-11-12 18:06
I'm not 100% sure the error and the shutdown are correlated - I just pushed a new version to npm that clears up some confusion with constants - try the new ver and see if it magically fixes anything.

**Comment by dave-irvine** [comment] 2015-11-12 18:18
I've updated, but same issue.

I've gone so far as to pull out the wireshark and I'm definitely seeing something odd.

When using the library, I'm seeing LDAP protocol data on the wire before the Server Hello SSL message appears. I think something in the library is trying to talk LDAP too quickly before the SSL negotiation is finished.

Here's a screenshot.
http://imgur.com/a/mi8Eh

The window on the left is using openssl as a client and works fine. On the right is ldap-client.

You can see where they diverge in packet 6.

**Comment by dave-irvine** [comment] 2015-11-12 18:23
Further screenshot 

http://imgur.com/qnXEPPJ

The one on the left is the latest version of the ldap-client, the one on the right is the old version that works.

**Comment by jeremycx** [comment] 2015-11-12 21:28
Looking at the caps, it certainly looks weird. What version of openLDAP libs are you on?

**Comment by dave-irvine** [comment] 2015-11-13 08:14
I'm on

```
Package: libldap2-dev
Architecture: amd64
Version: 2.4.31-1+nmu2ubuntu8.2
Replaces: libopenldap-dev
Provides: libldap-dev
Depends: libldap-2.4-2 (= 2.4.31-1+nmu2ubuntu8.2)
```

**Comment by dave-irvine** [comment] 2015-11-13 12:18
So I've been stracing the node process on the old working version and the new non-working version.

Ignoring the fact that I'm sure the ssl cert isnt the issue, there is definitely some weird behaviour. The new version doesn't ever try to load the ca root certificates, whereas the old version does.

In the old version:

```
[pid 15405] mprotect(0x7f6bb37db000, 28672, PROT_READ) = 0
[pid 15405] futex(0x7f6bb37e26c0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
[pid 15405] open("/etc/gnutls/pkcs11.conf", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15405] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 11
[pid 15405] fstat(11, {st_mode=S_IFREG|0644, st_size=275238, ...}) = 0
[pid 15405] fstat(11, {st_mode=S_IFREG|0644, st_size=275238, ...}) = 0
[pid 15405] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6bbca89000
```
but on the new version we jump straight to trying to resolve the dns name (and then initiating the connection, etc)

```
[pid 15541] mprotect(0x7f280e703000, 28672, PROT_READ) = 0
[pid 15541] futex(0x7f280e70a6c0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
[pid 15541] open("/etc/gnutls/pkcs11.conf", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15541] stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=257, ...}) = 0
```

It looks like the new version just doesn't try to load ssl certs from the certificate store. I think either this is the issue, or it is pointing to a bigger incompatibility with the underlying openssl implementation?

**Comment by jeremycx** [comment] 2015-11-13 16:22
Firstly, there was a lot of client fixes in openLDAP between .30 and (current) .42 - any way you can get libldap bumped up to 2.4.42?

There's some sense in looking at the lib versions: the old code used ldap_open, the new code is 100% async - only do-able because the new openLDAP client lib finally fixed a bunch of async bugs, so ordering is likely to be quite different.

--
behavio**u**r    <-  Thanks, brotha. Here's a Canadian Colour for ya: colour.

**Comment by jeremycx** [comment] 2015-11-13 16:28
Look at test/index.js -- it has lots of examples that work (for me, at least). Let's see if you can run the test suite.

* grab the current code from github
* ensure openLDAP client and server are installed
* `npm --install` will get you all the dev dependencies (incl. mocha)
* `cd test`
* `./run_server.sh`   <-- Might have to tweak paths a bit to run slapd and slapadd

Now you have a custom ldap server running on ports 1234 and 1235 with some basic demo data in it. In a separate terminal cd to node-LDAP and `npm test` will run all the tests against the demo server.

**Comment by jeremycx** [comment] 2015-11-13 16:29
Actually, the last message was intended for a different issue (#81). You can run the tests too, though, if you want :)

**Comment by jeremycx** [comment] 2015-11-17 21:29
Any updates? I'm really concerned about this issue...

**Comment by dave-irvine** [comment] 2015-11-18 11:55
So I finally got around to installing OpenLDAP clients and libraries from source, so I'm now on 2.4.42, unfortunately this still didn't fix the issue. :(

**Comment by jeremycx** [comment] 2015-11-18 16:19
OK, that was the easy thing to try. I'll start looking deeper on this end. Did you run the test suite with the enclosed server config (ie run ./test_server.sh and then run npm test)?

**Comment by dave-irvine** [comment] 2015-11-18 16:50
42 passing (11s)
  2 failing

  1) LDAP Should rename:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) LDAP Should fail to rename:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


All the TLS related ones seem to work

 LDAP TLS
    ✓ Should fail TLS on cert validation (2004ms)
    ✓ Should connect (48ms)
    ✓ Should search via TLS
    ✓ Should findandbind() (79ms)
    ✓ Should fail findandbind()
    ✓ Should still have TLS

**Comment by dave-irvine** [comment] 2015-11-18 16:57
OK, cancel my earlier statement, yes this now works with the latest client libraries.

I still had my validatecert set to LDAP.LDAP_OPT_X_TLS_TRY without having set up the CA certs on this test machine.

**Comment by jeremycx** [comment] 2015-11-18 17:03
Can you verify that it wasn't `LDAP.LDAP_OPT_X_TLS_TRY` all along? I need to know if I should put an openLDAP version check for `> X.42` in the compile step...

**Comment by dave-irvine** [comment] 2015-11-18 17:11
It still fails on my local machine on 2.4.31, I'm going to make a fresh Centos 7 vm and see what we get.

**Comment by dave-irvine** [comment] 2015-11-18 17:26
Ok this works on Centos 7 on 2.4.39

While I'm at it I'll test Centos 6 as well.

**Comment by dave-irvine** [comment] 2015-11-18 17:35
Centos 6 ships with 2.4.39 so I can't test anything older unfortunately. I wonder why Mint has such old libs.

**Comment by dave-irvine** [comment] 2015-11-18 17:40
Do you have a "buy me a beer/coffee" fund?

**Comment by jeremycx** [comment] 2015-11-18 18:27
Nope, but maybe think about this in lieu of coffee: https://ssimicro.com/software-developer-0

Thanks for your help!

**Closed by jeremycx** 2015-11-18 18:27 UTC

**Comment by dave-irvine** [comment] 2015-11-18 18:46
I'm in the UK, but thanks anyway!

**Comment by jeremycx** [comment] 2015-11-18 18:49
Canadian work visas are very VERY simple to acquire for the UK. There's still some small advantage for not revolting.

 :)
